var fonctions = [
 "Acheteur"
,"Adjoint au Maire"
,"Asset Manager"
,"Assistante"
,"Assistant Maîtrise d'Ouvrage"
,"Bureau d'étude"
,"Chargé d'affaire"
,"Chargé de clientèle"
,"Chargé de communication"
,"Chef de base"
,"Chef de cabinet"
,"Chef de division patrimoine"
,"Chef de projet"
,"Commandant"
,"Comptable"
,"Conseiller municipal"
,"Consultant"
,"Député Maire"
,"Directeur"
,"Directeur Achats"
,"Directeur Adjoint"
,"Directeur Administratif"
,"Directeur de Cabinet"
,"Directeur de Site"
,"Directeur des Opérations"
,"Directeur des Services Généraux"
,"Directeur des Services Techniques"
,"Directeur Développement Commercial"
,"Directeur du Développement Durable"
,"Directeur du Patrimoine"
,"Directeur Environnement"
,"Directeur Général"
,"Directeur Général des Services"
,"Directeur Immobilier"
,"Directeur Industriel"
,"Directeur Informatique"
,"Directeur Technique"
,"DRH"
,"Elu"
,"Fournisseur"
,"Gardien"
,"Gérant"
,"Gestionnaire Contrat"
,"Gestionnaire Immobilier"
,"Ingénieur d'études"
,"Lotisseur"
,"Maire"
,"Membre du conseil syndical"
,"Partenaire"
,"Préfet"
,"Président"
,"Président de la commission chauffage"
,"Président du conseil syndical"
,"Promoteur"
,"Property Manager"
,"Proviseur"
,"Relance"
,"Responsable Achats"
,"Responsable Administratif"
,"Responsable Bâtiment"
,"Responsable Commercial"
,"Responsable des Contrats"
,"Responsable de Site (Directeur / Responsable)"
,"Responsable des Services Généraux"
,"Responsable du Patrimoine"
,"Responsable Energie"
,"Responsable HSE"
,"Responsable Immobilier (Directeur / Responsable)"
,"Responsable Ingénierie"
,"Responsable Investissements"
,"Responsable Juridique"
,"Responsable Maintenance/Entretien"
,"Responsable Qualité"
,"Responsable Relations Publiques"
,"Responsable Sécurité"
,"Responsable Technique"
,"Responsable Travaux"
,"Secrétaire"
,"Secrétaire Général"
,"Sénateur Maire"
,"Sous Préfet"
,"SyndicTechnicien Maintenance"
,"Vice Président"
]